spring:
  webflux:
    base-path: /api/v1
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/user_service_db
    username: gad-dev
    password: 123456789
    pool:
      enabled: true
      initial-size: 5
      max-size: 15
      max-life-time: 300000ms
      max-idle-time: 60000ms
      max-create-connection-time: 5000ms
      validation-query: SELECT 1
      validation-depth: local
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8180/realms/ticketing-system-realm
  kafka:
    bootstrap-servers: localhost:9092
    #producer:
      #key-serializer: org.apache.kafka.common.serialization.StringSerializer
      #value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      #acks: all
      #retries: 3
      #properties:
        #spring.json.add.type.headers: false
        #max.in.flight.requests.per.connection: 5
        #enable.idempotence: true

app:
  kafka:
    topics:
      user-created: user.created.v1

logging:
  level:
    root: INFO
    com.ticketmaster: DEBUG
    io.r2dbc.postgresql.QUERY: DEBUG
    io.r2dbc.postgresql.PARAM: DEBUG
    org.springframework.data.r2dbc: DEBUG
    org.springframework.r2dbc: DEBUG
    io.r2dbc.pool: DEBUG
    org.springframework.transaction: DEBUG
server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}